### ISSUE TITLE
Album art is not loading.

### ISSUE THREAD

**Issue by DrBanana419** [yktoo/ymuse#25] opened 2020-12-24 12:49 UTC
I added album art to an mp3 file like this:
`
ffmpeg -i in.mp3 -i test.jpeg -map 0:0 -map 1:0 -codec copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" out.mp3
`
Is there anything I have to do in ymuse? I noticed 'track title template' in the preferences window doesn't include anything about album covers, do I have to edit that?

**Comment by yktoo** [comment] 2020-12-24 13:11
Duplicate of #16, you'll have to add a cover file.

**Closed by yktoo** 2020-12-24 13:11 UTC
